shell = "zsh"

# デフォルトを遅延読み込みにする
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# 遅延読み込みの設定 
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# zsh配下のファイルは遅延読み込みする
[plugins.local-defers]
local = "~/.dotfiles/.config/zsh"
use = ["defer/*.zsh"]

# zsh/sync配下のファイルは遅延読み込みしない
[plugins.local-sync]
local = "~/.dotfiles/.config/zsh"
use = ["sync/*.zsh"]
apply = ["source"]
