gui:
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  showIcons: true
  nerdFontsVersion: "3"
refresher:
  refreshInterval: 3
os:
  edit: "nvim"
